SweeEatProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('allauth.urls')),
    path('products/', include('products.urls')),
    path('reviews/', include('reviews.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls'))
]

cart/urls.py
from django.urls import path

import cart.views

urlpatterns = [
    path('add/<product_id>', cart.views.add_to_cart, name="add_to_cart"),
    path('view', cart.views.view_cart, name="view_cart"),
    path('remove/<product_id>', cart.views.remove_from_cart,
         name="remove_from_cart"),
    path('update_quantity/<product_id>',
         cart.views.update_quantity, name="update_cart_quantity")
]

products/urls.py
from django.contrib import admin
from django.urls import path, include
import products.views

urlpatterns = [
    path('', products.views.index, name='all_products_route'),
    path('all',
         products.views.show_products, name='manage_products_route'),
    path('create', products.views.create_product, name='create_product_route'),
    path('details/<product_id>',
         products.views.view_product, name='view_product_route'),
    path('update/<product_id>',
         products.views.edit_product, name='update_product_route'),
    path('delete/<product_id>',
         products.views.delete_product, name='delete_product_route'),
]

products/models.py
from django.db import models
from cloudinary.models import CloudinaryField


from django.core.validators import MinLengthValidator

# Create your models here.
class Tags(models.Model):
    title = models.CharField(blank=False, max_length=255)

    def __str__(self):
        return self.title

class Category(models.Model):
    title = models.CharField(blank=False, max_length=255)

    def __str__(self):
        return self.title

class Product(models.Model):
    name = models.CharField(blank=False, max_length=255, validators=[
                             MinLengthValidator(3)])
    description = models.TextField(blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tags)
    cover = CloudinaryField()

    def __str__(self):
        return self.name

reviews/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product

# Create your models here.

class Review(models.Model):
    title = models.CharField(max_length=255, blank=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    content = models.TextField(blank=False)
    date = models.DateField(blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

products/forms.py
from django import forms
from .models import Product, Tags, Category
from cloudinary.forms import CloudinaryJsFileField


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'category', 'tags', 'cover')
    cover = CloudinaryJsFileField()


class SearchForm(forms.Form):
    name = forms.CharField(max_length=100, required=False)
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(), required=False)
    price_below = forms.IntegerField(required=False)

products/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .models import Product
from .forms import ProductForm, SearchForm

# Create your views here.


def index(request):
    form = SearchForm(request.GET)
    if request.GET:
        query = ~Q(pk__in=[])

        if 'name' in request.GET and request.GET['name']:
            name = request.GET['name']
            query = query & Q(name__icontains=name)

        if 'category' in request.GET and request.GET['category']:
            category_id = request.GET['category']
            query = query & Q(category=category_id)

        if 'price_below' in request.GET and request.GET['price_below']:
            price_below = request.GET['price_below']
            price_query = Q(price__lte=price_below)
            query = query & price_query

        products = Product.objects.all()
        products = products.filter(query)

        return render(request, 'products/index.template.html', {
            'form': form,
            'products': products
        })

    else:
        products = Product.objects.all()
        return render(request, 'products/index.template.html', {
            'form': form,
            'products': products
        })


def show_products(request):
    form = SearchForm(request.GET)
    if request.GET:
        query = ~Q(pk__in=[])

        if 'name' in request.GET and request.GET['name']:
            name = request.GET['name']
            query = query & Q(name__icontains=name)

        if 'category' in request.GET and request.GET['category']:
            category_id = request.GET['category']
            query = query & Q(category=category_id)

        if 'price_below' in request.GET and request.GET['price_below']:
            price_below = request.GET['price_below']
            price_query = Q(price__lte=price_below)
            query = query & price_query

        products = Product.objects.all()
        products = products.filter(query)

        return render(request, 'products/all_products.template.html', {
            'form': form,
            'products': products
        })

    else:
        products = Product.objects.all()
        return render(request, 'products/all_products.template.html', {
            'form': form,
            'products': products
        })

# def show_products(request):
#     all_products = Product.objects.all()
#     return render(request, 'products/all_products.template.html', {
#         'products': all_products
#     })


@login_required
def create_product(request):
    if request.method == "POST":
        form = ProductForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, "New product has been added")
            return redirect(reverse(show_products))

        else:
            return render(request, 'products/create_product.template.html', {
                'form': form
            })

    else:
        form = ProductForm()
        return render(request, 'products/create_product.template.html', {
            'form': form
        })


def view_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'products/details.template.html', {
        'product': product
    })


def edit_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect(reverse(show_products))
        else:
            return render(request, 'products/edit_product.template.html', {
                'form': form,
                'product': product
            })
    else:
        form = ProductForm(instance=product)
        return render(request, 'products/edit_product.template.html', {
            'form': form,
            'product': product
        })


def delete_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == "POST":
        product.delete()
        return redirect(reverse(show_products))
    else:
        return render(request, 'products/confirm_delete_product.template.html', {
            'product': product
        })

products/templates/products/all_products.template.html
{% extends 'base.template.html'%}
{% load cloudinary %}
{%load static%}
{%load crispy_forms_tags%}

{%block title%}Admin Panel{%endblock%}

{%block content%}
<!--Crispy Form Styling-->
<style>
#div_id_name {
  font-family: "Lato", sans-serif;
  font-size: 16px;
  color: #ff644e;
  padding-top: 20px;
}

#div_id_category {
  font-family: "Lato", sans-serif;
  font-size: 16px;
  color: #ff644e;
}

#div_id_price_below {
  font-family: "Lato", sans-serif;
  font-size: 16px;
  color: #ff644e;
  
}

.numberinput, .textinput, .select{
  border: 1px solid #ff968d;
  width: 100%
}

#id_category, #id_name, #id_price_below {
  font-family: "Lato", sans-serif;
  font-size: 16px;
  color: #ff644e;
}

input {
  font-family: "Lato", sans-serif;
  font-size: 18px;
  color: white;
  background-color: #ff968d;
  padding: 10px 40px;
  border: 0px;
}

input:hover {
  background: #f41f4e;
  color: white;
  border: 0px;
}
</style>
<div class="container fluid">
<p class="text-center admin-text">Hi {{request.user}}, this page is strictly for admin access only.</p>
</div>
{% if request.user.is_superuser %}
    <div class="pt-3 pb-5 text-center">
        <a class="btn-custom-2" style="text-decoration: none" href="{% url 'create_product_route' %}"><i class="fas fa-plus-circle"></i>  Add New Product</a>
    </div>
	<h2 class="h2-admin text-center">Manage Products</h2>
    
    <div class="coljustify-content-center">
            <form method="GET">
                {{form|crispy}}
                <input type="submit" value="Search"/>
            </form>
    </div>
	
         <div class="card-column row d-flex justify-content-around">
       
        {%for product in products %}
        
            <div class="card mt-4" style="width: 20rem;" >
                {% cloudinary product.cover class="card-img-top" crop="fill"%}

                
				<div class="card-body">
					<a style="text-decoration: none" href="{% url 'view_product_route' product_id=product.id %}">
						<h5 class="card-title card-title-admin">{{product.name}}</h5>
					</a>
					<p class="card-text">{{product.description}}</p>
				
					<div class="d-flex justify-content-center">
						<a class="col-6 text-view text-center" style="text-decoration: none" href="{% url 'update_product_route' product_id=product.id %}">Edit&nbsp;&nbsp;<i class="far fa-edit"></i></a>
						<a class="col-6 text-view text-center" style="text-decoration: none" href="{% url 'delete_product_route' product_id=product.id %}">Delete&nbsp;&nbsp;<i class="far fa-trash-alt"></i></a>
					</div>

                    <div class="card-footer mt-2">
                        <small class="text-muted">{{product.category}}</small>
                    </div>
                </div>
            </div>
        {%endfor%}
        </div>
{% endif %}
{%endblock%}

products/templates/products/confirm_delete_product.template.html
{% extends 'base.template.html'%}
{% load cloudinary %}
{%load static%}

{%block title%}Delete Product{%endblock%}

{%block content%}
	<h2 class="h2-ctm-d">Delete {{product.name}}</h2>
	
	<div class="row mt-4 mb-2">
		<div class="col-sm-6 media cards-gallery">
			{% cloudinary product.cover class="img-fluid"%}
		</div>
	
		<div class="col-sm-6 align-self-center align-items-center">
			<div class="col-sm-12">
				<h2 class="h2-ctm-d mt-2">{{product.name}}</h2>
				<h3 class="h3-ctm-d">{{product.category}}</h3>
	
				<div class="col-sm-12 p-0">
					<h3 class="h3-ctm-d">${{product.price}}</h3>
				</div>
	
				<div class="col-sm-12 p-0 m-0">
					<h4 class="m-0 h4-ctm-d mt-3 mb-3">{{product.description}}</h4>
				</div>
	
				<div class="col-sm-12 p-0 mb-2">
					{%for tag in product.tags.all %}
					<span class="badge badge-pill">{{tag.title}}</span>
					{%endfor%}
				</div>
			</div>
		</div>
	</div>
	
	<h3 class="h3-ctm-rd">Are you sure?</h3>
	<form method="POST">
		{%csrf_token%}
		<input class="btn btn-review" type="submit" value="Confirm">
		<a class="btn btn-review" href="{% url 'manage_products_route'%}">Cancel</a>
	</form>
{%endblock%}

products/templates/products/create_product.template.html
{% extends 'base.template.html'%}
{%load crispy_forms_tags%}
{% load cloudinary %}
{%load static%}

{%block title%}Create Product{%endblock%}

{%block content%}
<!--Crispy Form Styling-->
<style>
label {
  font-family: "Lato", sans-serif;
  font-size: 16px;
  color: #ff644e;
  padding-top: 20px;
}

.form-control{
  border: 1px solid #ff968d;
  width: 100%
}

.textInput, .textarea, .numberinput, .select, .selectmultiple {
  font-family: "Lato", sans-serif;
  font-size: 16px;
  color: #ff644e;
}
</style>

    <h2 class="h2-ctm-d">Create Product</h2>
    <form method="POST" enctype="multipart/form-data" id="form">    
    {%csrf_token%}
        {{form|crispy}}
        <input class="btn-product" type="submit">
    </form>

	<div class="status">
		<h2>Status</h2>
		<span class="status_value">Idle</span>
	</div>
	
	<div class="uploaded_info_holder">
	</div>
{%endblock%}

{%block js %}
	{% cloudinary_includes %}
	{% cloudinary_js_config %}
	<script>
		function prettydump(obj) {
            ret = ""
            $.each(obj, function(key, value) {
            ret += "<tr><td>" + key + "</td><td>" + value + "</td></tr>";
            });
            return ret;
        }

        // jQuery ready
        $(function(){
            $("#form input[type='file']").cloudinary_fileupload({
                dropZone:"#form",
                start: function() {
                    console.log("Starting upload...")
                    $('.status_value').text("Starting direct upload...")
                },
                progress:function() {
                    console.log("uploading...")
                    $('.status_value').text("Uploading...");
                }
            }).on("cloudinarydone", function(e, data){
               $('.status_value').text("Upload done");

               // for debugging
                var info = $('<div class="uploaded_info"/>');
                        $(info).append($('<div class="image"/>').append(
                        $.cloudinary.image(data.result.public_id, {
                        format: data.result.format, width: 150, height: 150, crop: "fill"
                    })
                ));
                $('.uploaded_info_holder').append(info);
                $("#form input[type='file']").parent().parent().remove();
            })  
        }) // end $(function
    </script>

{%endblock%}

products/templates/products/details.template.html
{% extends 'base.template.html'%}
{% load cloudinary %}
{%load static%}

{%block title%}Show All Products{%endblock%}



{%block content%}

				<div class="row mt-4 mb-2">
					<div class="col-sm-6 media cards-gallery">
                        {% cloudinary product.cover class="img-fluid"%}
					</div>

					<div class="col-sm-6 align-self-center align-items-center">
                        <div class="col-sm-12">
                            <h2 class="h2-ctm-d mt-2">{{product.name}}</h2>
                            <h3 class="h3-ctm-d">{{product.category}}</h3>

                            <div class="col-sm-12 p-0">
                                <h3 class="h3-ctm-d">${{product.price}}</h3>
                            </div>
                            
                            <div class="col-sm-12 p-0 m-0">
                            <h4 class="m-0 h4-ctm-d mt-3 mb-3">{{product.description}}</h4>
                            </div>

                            <div class="col-sm-12 p-0 mb-2">
                            {%for tag in product.tags.all %}
                            <span class="badge badge-pill">{{tag.title}}</span>
                            {%endfor%}
                            </div>

                            <div class="mt-3">
							{% if not request.user.is_authenticated %}
							<p class="h4-ctm-d">To make a purchase, please <a href="{%url 'account_login'%}">Sign in</a> or <a href="{%url 'account_signup'%}">Register an account</a> with us.</p>
							{% endif %}
							{% if request.user.is_authenticated %}
							<a class="btn btn-cart" href="{% url 'add_to_cart' product_id=product.id %}">Add to Cart&nbsp;<i class="fa fa-cart-plus" aria-hidden="true"></i></a>
                                <a class="btn btn-review" href="{% url 'create_review_route' product_id=product.id %}">Add a Review&nbsp;<i class="far fa-comments"></i></a>
							{% endif %}

							{% if request.user.is_superuser %}
                            <div class="pt-1">
							<br><a class="btn btn-edit" href="{% url 'update_product_route' product_id=product.id %}">Edit</a>
                                <a class="btn btn-delete" href="{% url 'delete_product_route' product_id=product.id %}">Delete</a>
                            </div>
							{% endif %}
                            </div>

                            <div class="pt-5">
                                <a href="{% url 'all_products_route' %}" role="button" class="text-shop" style="text-decoration: none"><i class="fas fa-arrow-circle-left"></i> continue shopping <i class="fas fa-store"></i></a>
                            </div>
					    </div>
				    </div>
				</div>
                <div>
                

                <h2 class="mt-4 h2-ctm-d">Reviews</h2>
                {%for review in product.review_set.all %}
                    <div class="card">
                        <div class="card-body">
                            <div class="card-title">
                            <h2>{{review.title}}</h2>
                            </div>

                            <div>
                            <h3 class="h3-ctm-r">{{review.content}}</h3>
                            </div>

                            <p class="h4-ctm-r">Commented by {{review.user.username}} on {{review.date}}</p>

                            {% if request.user.is_authenticated %}
                            <div class="d-flex justify-content-end">
                            <a class="text-edit-r" style="text-decoration: none" href="{% url 'update_review_route' review_id=review.id %}"><i class="far fa-edit"></i></a>
                            <a class="text-edit-r pl-3" href="{% url 'delete_review_route' review_id=review.id %}"><i class="far fa-trash-alt"></i></a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                {%endfor%}

                </div>


{%endblock%}

products/templates/products/edit_product.template.html
{% extends 'base.template.html'%}
{%load crispy_forms_tags%}
{% load cloudinary %}
{%load static%}

{%block title%}Index{%endblock%}

{%block content%}
<!--Crispy Form Styling-->
<style>
label {
  font-family: "Lato", sans-serif;
  font-size: 16px;
  color: #ff644e;
  padding-top: 20px;
}

.form-control{
  border: 1px solid #ff968d;
  width: 100%
}

.textInput, .textarea, .numberinput, .select, .selectmultiple {
  font-family: "Lato", sans-serif;
  font-size: 16px;
  color: #ff644e;
}
</style>
    <h2 class="h2-ctm-d">Edit {{product.name}}</h2> 
    <form method="POST" enctype="multipart/form-data" id="form">    
    {%csrf_token%}
        {{form|crispy}}

        
        <div class="row mt-1 mb-2">
            <div class="col-3 product-text"><p>Original Image</p></div>
            <div class="col-3 product-text"><p>Updated Image <span class="status_value"></span></p></div>
        </div>
        <div class="row mt-1 mb-2">
            <div class="col-3">{% cloudinary product.cover width=150 height=150 crop="fill"%}</div>
            <div class="col-3 uploaded_info_holder"></div>
        </div>


        <input class="btn-product" type="submit" name="Update Product">
    </form>
{%endblock%}

{% block js %}
	{% cloudinary_includes %}
	{% cloudinary_js_config %}
	<script>
		function prettydump(obj) {
            ret = ""
            $.each(obj, function(key, value) {
            ret += "<tr><td>" + key + "</td><td>" + value + "</td></tr>";
            });
            return ret;
        }

        $(function(){
            $("#form input[type='file']").cloudinary_fileupload({
                dropZone:"#form",
                start: function() {
                    console.log("Starting upload...")
                    $('.status_value').text("Starting direct upload...")
                },
                progress:function() {
                    console.log("uploading...")
                    $('.status_value').text("Uploading...");
                }
            }).on("cloudinarydone", function(e, data){
               $('.status_value').text("Upload done");

                var info = $('<div class="uploaded_info"/>');
                        $(info).append($('<div class="image"/>').append(
                        $.cloudinary.image(data.result.public_id, {
                        format: data.result.format, width: 150, height: 150, crop: "fill"
                    })
                ));
                $('.uploaded_info_holder').append(info);

                $("#form input[type='file']").parent().parent().remove();
            })  
        })
    </script>

{% endblock %}

products/templates/products/index.template.html
{% extends 'base.template.html'%}
{% load cloudinary %}
{%load static%}
{%load crispy_forms_tags%}


{%block title%}Sweet Selections{%endblock%}

{%block content%}

<!--Crispy Form Styling-->
<style>
#div_id_name {
  font-family: "Lato", sans-serif;
  font-size: 16px;
  color: #ff644e;
  padding-top: 20px;
}

#div_id_category {
  font-family: "Lato", sans-serif;
  font-size: 16px;
  color: #ff644e;
}

#div_id_price_below {
  font-family: "Lato", sans-serif;
  font-size: 16px;
  color: #ff644e;
  
}

.numberinput, .textinput, .select{
  border: 1px solid #ff968d;
  width: 100%
}

#id_category, #id_name, #id_price_below {
  font-family: "Lato", sans-serif;
  font-size: 16px;
  color: #ff644e;
}

input {
  font-family: "Lato", sans-serif;
  font-size: 18px;
  color: white;
  background-color: #ff968d;
  padding: 10px 40px;
  border: 0px;
}

input:hover {
  background: #f41f4e;
  color: white;
  border: 0px;
}
</style>



<h2 class="h2-ctm text-center">Sweet Selections</h2>
    <div class="row">
        <div class="col-md-3 col-12 justify-content-center">
            <form method="GET">
                {{form|crispy}}
                <input type="submit" value="search"/>
            </form>
        </div>

        <div class="col-md-9 col-12">
            <div class="card-column row d-flex justify-content-around">
                {%for product in products %}
                    
                        <div class="card mt-4" style="width: 20rem;">
                            {% cloudinary product.cover class="card-img-top" crop="fill"%}
                            <div class="card-body">
                                <h5 class="card-title">{{product.name}}</h5>
                                <p class="card-text">${{product.price}}</p>
                                <p class="card-text">{{product.description}}</p>

                                <div class="d-flex justify-content-center">
                                    <div>
                                    <a href="{% url 'view_product_route' product_id=product.id %}" class="col-6 text-view text-center" style="text-decoration: none">View More&nbsp;&nbsp;<i class="fas fa-eye"></i></a>
                                    </div>

                                    {% if request.user.is_authenticated %}
                                    <div>
                                    <a href="{% url 'add_to_cart' product_id=product.id %}" class="col-6 text-view text-center" style="text-decoration: none">Add to Cart&nbsp;<i class="fas fa-cart-plus"></i></a>
                                    </div>
                                    {% endif %}
                                </div>
                                        
                                <div class="card-footer mt-2">
                                    <small class="text-muted">{{product.category}}</small>
                                </div>
                            </div>
                        </div>
                {%endfor%}
            </div>
        </div>
        
    </div>
{%endblock%}